alertmanager:
  ## If false, alertmanager will not be installed
  ##
  enabled: false

## Monitors ConfigMap changes and POSTs to a URL
## Ref: https://github.com/jimmidyson/configmap-reload
##
configmapReload:
  alertmanager:
    ## If false, the configmap-reload container will not be deployed
    ##
    enabled: false

kubeStateMetrics:
  ## If false, kube-state-metrics sub-chart will not be installed
  ##
  enabled: true

nodeExporter:
  ## If false, node-exporter will not be installed
  ##
  enabled: true


pushgateway:
  ## If false, pushgateway will not be installed
  ##
  enabled: false

# adds additional scrape configs to prometheus.yml
# must be a string so you have to add a | after extraScrapeConfigs:
# example adds prometheus-blackbox-exporter scrape config
extraScrapeConfigs: {}
