apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: strimzi-entity-operator-delegation
subjects:
  - kind: ServiceAccount
    name: strimzi-entity-operator
    namespace: kafka-docker
roleRef:
  kind: ClusterRole
  name: strimzi-entity-operator
  apiGroup: rbac.authorization.k8s.io
