apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: kafka-docker
  name: test
  namespace: kafka-docker
spec:
  partitions: 3
  replicas: 1
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: kafka-docker
  name: replication-test-2
  namespace: kafka-docker
spec:
  partitions: 3
  replicas: 2
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaTopic
metadata:
  labels:
    strimzi.io/cluster: kafka-docker
  name: replication-test-3
  namespace: kafka-docker
spec:
  partitions: 3
  replicas: 3
