apiVersion: v1
kind: Secret
metadata:
  name: client-user-password
  namespace: kafka-k8s
type: Opaque
stringData:
  password: clientclient
---
apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaUser
metadata:
  labels:
    strimzi.io/cluster: kafka-k8s
  name: client
  namespace: kafka-k8s
spec:
  authentication:
    type: scram-sha-512
    password:
      valueFrom:
        secretKeyRef:
          key: password
          name: client-user-password
  authorization:
    acls:
      - host: "*"
        operation: Read
        resource:
          name: replication-test-2
          patternType: literal
          type: topic
      - host: "*"
        operation: Write
        resource:
          name: replication-test-2
          patternType: literal
          type: topic
      - host: "*"
        operation: Describe
        resource:
          name: replication-test-2
          patternType: literal
          type: topic

      - host: "*"
        operation: All
        resource:
          name: test
          patternType: literal
          type: group
    type: simple
